// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQx-ccCMXtQSeeaaJQuS-zcGh_jklmKRI',
    appId: '1:832374259175:web:37e707cf342b5706149142',
    messagingSenderId: '832374259175',
    projectId: 'ecommerce-835d3',
    authDomain: 'ecommerce-835d3.firebaseapp.com',
    storageBucket: 'ecommerce-835d3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZqSTT22O8MTIYb_WwDn1QZJmkXB1paGY',
    appId: '1:832374259175:android:b80f62695075db26149142',
    messagingSenderId: '832374259175',
    projectId: 'ecommerce-835d3',
    storageBucket: 'ecommerce-835d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-ZZUK-lDzEgpRRNTECEjijdAFTJ2y41M',
    appId: '1:832374259175:ios:a7bea97fe9dda1a5149142',
    messagingSenderId: '832374259175',
    projectId: 'ecommerce-835d3',
    storageBucket: 'ecommerce-835d3.appspot.com',
    iosBundleId: 'com.example.ecommerceLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-ZZUK-lDzEgpRRNTECEjijdAFTJ2y41M',
    appId: '1:832374259175:ios:145a558613d5525d149142',
    messagingSenderId: '832374259175',
    projectId: 'ecommerce-835d3',
    storageBucket: 'ecommerce-835d3.appspot.com',
    iosBundleId: 'com.example.ecommerceLogin.RunnerTests',
  );
}
